### ISSUE TITLE
Add "variable fonts" option

### ISSUE THREAD

**Issue by Rvervuurt** [nuxt-modules/google-fonts#164]
I would like to add fonts as [variable fonts](https://fonts.google.com/knowledge/using_type/loading_variable_fonts_on_the_web), but this doesn't seem supported.

Now, adding fonts looks like this:
```
googleFonts: { 
    families: {
      'Inter+Tight': [200,400,600,700],
      'Alegreya': true,
    }
  },
```

But this just adds 200, 400, 600 and 700 font weights and doesn't allow for animation of the font weight.

According to Google's own documentation, variable fonts are added as a range (`200..700`) instead of steps (`200,400,600,700`), so the above could could look like this:

```
googleFonts: { 
    families: {
      'Inter+Tight': [200..700],
      'Alegreya': true,
    }
  },
```

Is this something you could consider adding?

**Comment by Rvervuurt** [comment]
This works:
```
googleFonts: { 
    families: {
      'Inter+Tight': [200 + '..' + 700],
      'Alegreya': true,
    }
  },
```

But VScode returns an error:
<img width="460" alt="billede" src="https://github.com/nuxt-modules/google-fonts/assets/1439765/b7af6846-9038-4773-824b-88b56320c38d">

**Comment by Rvervuurt** [comment]
> Hi @Rvervuurt You can use it like this:
> 
> ```
> googleFonts: { 
>     families: {
>       'Inter+Tight': '200..700',
>     }
>   },
> ```

Ah yes, much better! This doesn't trigger an error.
Good idea with adding it to the documentation.

**Comment by dukio** [comment]
> Hi @Rvervuurt You can use it like this:
> 
> ```
> googleFonts: { 
>     families: {
>       'Inter+Tight': '200..700',
>     }
>   },
> ```

Hi, this works as expected while in development but once the nuxt app is built the font doesn't work... is it just me or is someone else experiencing this issue?
The font I'm trying: [Manrope](https://fonts.google.com/specimen/Manrope) `[200..800]`

Once built it outputs this inside the `<style>` tag in HTML:
```css
@font-face {
    font-display: swap;
    font-family: Manrope;
    font-style: normal;
    font-weight: 200 800;
    src: url(/_nuxt/Manrope-200 800-2.26287892.woff2) format('woff2');
    unicode-range: u+0301, u+0400-045f, u+0490-0491, u+04b0-04b1, u+2116;
  }
  ```
That `src url()` is not valid, should be enclosed in quotes. The actual files in `.output/public/fonts` have a space in the name:
![image](https://github.com/nuxt-modules/google-fonts/assets/2744227/7b3892b8-7eaa-44e0-9381-6d1a4883cb09)


You can see a reproduction here: https://debugfontissue.davidegaio.com/ (user: `test`, pass: `test`)
Config:
```
families: {
    Manrope: '200..800',
}
```
---
Note: I'm replying here because I think it's related to this issue but if you prefer I can create a new issue for this, let me know
